name: lutris
base: core22
adopt-info: lutris
grade: stable
confinement: strict
compression: lzo
license: GPL-3.0-only
source-code: https://git.launchpad.net/lutris-snap/tree/snapcraft.yaml
issues:
  - https://github.com/sameersharma2006/lutris-snap/issues
  - https://bugs.launchpad.net/lutris-snap
architectures:
  - build-on: amd64
  
apps: 
  lutris:
    command: usr/bin/lutris
    extensions: [gnome]
    environment:
      APPIMAGE_EXTRACT_AND_RUN: 1
      PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages:${SNAP}/usr/local/lib/python3.10/dist-packages
    common-id: net.lutris.Lutris 
    desktop: usr/share/applications/net.lutris.Lutris.desktop 
    plugs:
      - home
      - unity7
      - network
      - network-bind
      - network-status
      - audio-record
      - audio-playback
      - bluez
      - browser-support
      - joystick
      - removable-media
      - optical-drive
      - screen-inhibit-control
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - upower-observe

slots:    
  lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris  
  
parts:
  lutris:
    source: https://github.com/lutris/lutris.git
    source-tag: v0.5.16
    plugin: meson
    parse-info: [usr/share/metainfo/net.lutris.Lutris.metainfo.xml]
    meson-parameters:
      - --prefix=/usr
    override-pull: |
      craftctl default
      sed -e 's|Icon=lutris|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/lutris.svg|' -i  share/applications/net.lutris.Lutris.desktop 
  
  deps:
    after: [lutris]
    plugin: nil
    stage-packages:
      - psmisc
      - cabextract
      - unzip
      - p7zip
      - curl
      - fluid-soundfont-gs
      - mesa-utils
      - vulkan-tools 
    prime:
      - bin/fuser
      - usr/bin/killall
      - usr/bin/peekfd
      - usr/bin/prtstat
      - usr/bin/pslog
      - usr/bin/pstree
      - usr/share/menu/psmisc
      - usr/share/pixmaps/pstree16.xpm
      - usr/share/pixmaps/pstree32.xpm
      - usr/bin/cabextract
      - usr/share/icons/cab_extract.png
      - usr/share/icons/cab_view.png
      - usr/bin/funzip
      - usr/bin/unzip
      - usr/bin/unzipsfx
      - usr/bin/zipgrep
      - usr/bin/zipinfo
      - usr/lib/mime/packages/unzip
      - usr/bin/7zr
      - usr/bin/p7zip
      - usr/lib/p7zip/7zr
      - usr/bin/curl
      - usr/share/zsh/vendor-completions/_curl
      - usr/share/sounds/sf2/FluidR3_GS.sf2
      - usr/share/mesa-demos
      - usr/bin/vkcube
      - usr/bin/vkcubepp
      - usr/bin/vulkaninfo

  py-deps:
    after: [deps]
    plugin: nil
    stage-packages:
      - python3-pil
      - python3-distro
      - python3-requests
      - python3-protobuf
      - python3-lxml
      - python3-yaml
      - python3-gi
      - python3-gi-cairo
      - python3-setproctitle
      - python3-magic
      - python3-dbus
      - python3-evdev
    prime:
      - usr/lib/python3

  wine-deps:
    after: [py-deps]
    plugin: nil
    stage-packages:
      - libwine
      - winetricks
      - fluidsynth
      - gamemode
    prime:
      - usr/lib/*/wine
      - usr/share/wine
      - usr/bin/winetricks
      - usr/share/bash-completion/completions/winetricks
      - usr/share/icons/hicolor/scalable/apps/winetricks.svg
      - usr/share/metainfo/winetricks.appdata.xml
      - usr/bin/fluidsynth
      - usr/games
      - usr/bin/gamemoded
      - usr/lib/systemd/user/gamemoded.service
      - usr/libexec/cpugovctl
      - usr/libexec/gpuclockctl
      - usr/share/dbus-1/services/com.feralinteractive.GameMode.service
      - usr/share/gamemode
      - usr/lib/*/libgamemode
