name: lutris
base: core22
adopt-info: lutris
grade: stable
confinement: strict
compression: lzo
license: GPL-3.0-only
architectures:
  - build-on: amd64

assumes:
  - snapd2.54


lint:
  ignore:
    - library:
      - usr/lib/*/libmagic.so*
      
apps: 
  lutris:
    command: usr/bin/lutris
    extensions: [gnome]
    environment:
      APPIMAGE_EXTRACT_AND_RUN: 1
      PYTHONPATH: ${SNAP}/lib/python3.10/site-packages:${SNAP}/usr/lib/python3/dist-packages:${SNAP}/usr/local/lib/python3.10/dist-packages
      LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$SNAP/usr/local/bin
    common-id: net.lutris.Lutris 
    desktop: usr/share/applications/net.lutris.Lutris.desktop 
    plugs:
      - home
      - unity7
      - network
      - network-bind
      - network-status
      - audio-record
      - audio-playback
      - bluez
      - browser-support
      - joystick
      - removable-media
      - optical-drive
      - screen-inhibit-control
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - physical-memory-observe
      - upower-observe
      
slots:    
  lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris  
  
parts:
  lutris:
    source: https://github.com/lutris/lutris.git
    source-tag: v0.5.13
    plugin: meson
    parse-info: [usr/share/metainfo/net.lutris.Lutris.metainfo.xml]
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
    override-pull: |
      craftctl default
      sed -e 's|Icon=lutris|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/lutris.svg|' -i  share/applications/net.lutris.Lutris.desktop 
  
  deps:
    after: [lutris]
    plugin: nil
    stage-packages:
      - pciutils
      - libpci3
      - libmagic1
    stage:
      - usr/bin/lspci
      - usr/bin/setpci
      - usr/sbin/update-pciids
      - usr/lib/*/libpci.so*
      - usr/lib/*/libmagic.so*
    
  pydeps:
    after: [deps]
    plugin: nil
    override-build: |
      craftctl default
      pip install --prefix=$CRAFT_PART_INSTALL/usr Pillow==10.0.0
      pip install --prefix=$CRAFT_PART_INSTALL/usr requests==2.31.0
      pip install --prefix=$CRAFT_PART_INSTALL/usr Yaml8==0.1.2
      pip install --prefix=$CRAFT_PART_INSTALL/usr distro==1.8.0 
      pip install --prefix=$CRAFT_PART_INSTALL/usr setproctitle==1.3.2 
      pip install --prefix=$CRAFT_PART_INSTALL/usr python-magic==0.4.27
      pip install --prefix=$CRAFT_PART_INSTALL/usr lxml==4.9.3
     
  cleanup:
    after: [pydeps]
    plugin: nil
    build-snaps: [core22, gtk-common-themes, gnome-42-2204]
    override-prime: |
      set -eux
      for snap in "core22" "gtk-common-themes" "gnome-42-2204"; do
        cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$CRAFT_PRIME/{}" \;
      done   
