name: lutris
base: core20
adopt-info: lutris
grade: stable
confinement: strict
compression: lzo
license: GPL-3.0-only
architectures:
  - build-on: amd64

assumes:
  - snapd2.55
  - command-chain

lint:
  ignore:
    - library:
        - usr/lib/*/libmagic.so*
        - usr/lib/*/libXss.so*
        - usr/lib/*/libSDL2-2.0.so*
        - usr/lib/*/libffi.so*
        - usr/lib/*/libdecor-0.so*
        - usr/lib/*/libXv.so*

layout:
  /usr/share/zenity:
    bind: $SNAP/usr/share/zenity 
  
apps: 
  lutris:
    command-chain:
      - bin/migrate-config
    command: usr/bin/lutris
    extensions: [gnome-3-38]
    environment:
      APPIMAGE_EXTRACT_AND_RUN: 1
      PYTHONPATH: ${SNAP}/lib64/python3.8/site-packages:${SNAP}/lib/python3.8/site-packages:${SNAP}/usr/lib/python3/dist-packages:${SNAP}/usr/local/lib/python3.8/dist-packages
      TMPDIR: $XDG_RUNTIME_DIR
    common-id: net.lutris.Lutris 
    desktop: usr/share/applications/net.lutris.Lutris.desktop 
    plugs:
      - home
      - unity7
      - network
      - network-bind
      - network-status
      - audio-record
      - audio-playback
      - bluez
      - browser-support
      - joystick
      - removable-media
      - optical-drive
      - screen-inhibit-control
      - process-control
      - hardware-observe
      - mount-observe
      - system-observe
      - upower-observe

plugs:
  lutris-user-config:
    interface: personal-files
    read:
      - $HOME/.config/lutris
      - $HOME/.local/share/lutris   
      
slots:    
  lutris:
    interface: dbus
    bus: session
    name: net.lutris.Lutris  
  
parts:
  lutris:
    source: https://github.com/lutris/lutris.git
    parse-info: [usr/share/metainfo/net.lutris.Lutris.metainfo.xml]
    plugin: meson
    meson-version: 1.2.1 
    meson-parameters:
      - --prefix=/usr
    override-pull: |
      snapcraftctl pull
      sed -e 's|Icon=lutris|Icon=${SNAP}/usr/share/icons/hicolor/scalable/apps/lutris.svg|' -i  share/applications/net.lutris.Lutris.desktop 
  
  deps:
    after: [lutris]
    plugin: nil
    stage-packages:
      - pciutils
      - libpci3
      - libmagic1
      - x11-xserver-utils
      - mesa-utils
      - mesa-utils-bin
      - vulkan-tools
      - psmisc 
      - cabextract 
      - p7zip
      - libmspack0
      - libxss1
      - unzip 
      - libsdl2-2.0-0
      - libdecor-0-0
      - libxv1
    stage:
      - usr/bin/lspci
      - usr/bin/setpci
      - usr/bin/xrandr
      - usr/sbin/update-pciids
      - usr/lib/*/libpci.so*
      - usr/lib/*/libmagic.so*
      - usr/bin/glx*
      - usr/bin/vk*
      - usr/bin/vulkaninfo
      - bin/fuser
      - usr/bin/cabextract
      - usr/bin/7zr
      - usr/bin/p7zip
      - usr/lib/p7zip
      - usr/lib/*/libmspack*
      - usr/lib/*/libXss.so*
      - usr/bin/funzip
      - usr/bin/unzip*
      - usr/bin/zip*
      - usr/lib/mime/packages/unzip
      - usr/lib/*/libSDL2-2.0.so*
      - usr/lib/*/libdecor-0.so*
      - usr/lib/*/libXv.so*
    prime:
      - -usr/bin/$SNAPCRAFT_ARCH_TRIPLET-cpp*  
      
  pydeps:
    after: [deps]
    plugin: nil
    override-build: |
      craftctl default
      pip install --prefix=$SNAPCRAFT_PART_INSTALL/usr Pillow==10.0.0
      pip install --prefix=$SNAPCRAFT_PART_INSTALL/usr requests==2.31.0
      pip install --prefix=$SNAPCRAFT_PART_INSTALL/usr Yaml8==0.1.2
      pip install --prefix=$SNAPCRAFT_PART_INSTALL/usr distro==1.8.0 
      pip install --prefix=$SNAPCRAFT_PART_INSTALL/usr setproctitle==1.3.2 
      pip install --prefix=$SNAPCRAFT_PART_INSTALL/usr python-magic==0.4.27
      pip install --prefix=$SNAPCRAFT_PART_INSTALL/usr lxml==4.9.3
      pip install --prefix=$SNAPCRAFT_PART_INSTALL/usr protobuf==3.20.3
      pip install --prefix=$SNAPCRAFT_PART_INSTALL/usr moddb==0.8.1
      pip install --prefix=$SNAPCRAFT_PART_INSTALL/usr pypresence==4.3.0
  
  evdev:
    after: [pydeps]
    plugin: python
    source: https://files.pythonhosted.org/packages/05/50/629b011a7f61cb2fca754ea8631575784bf8605a1ec4d6970a010bc54e2b/evdev-1.6.1.tar.gz
    source-checksum: sha256/299db8628cc73b237fc1cc57d3c2948faa0756e2a58b6194b5bf81dc2081f1e3
    build-environment:
      - PATH: ${SNAPCRAFT_PART_INSTALL}/bin:${PATH}
      - PYTHONPATH: ""
    stage:
      - -bin/activate*
      - -bin/Activate.ps1
      - -bin/python
      - -bin/python3*
      - -bin/pip*
      - -bin/wheel*
      - -pyvenv.cfg
      - -lib/**/setuptools*
      - -lib/**/pip*
      - -lib/**/wheel*
      - -share/python-wheels
      - -share/doc
      - -share/man
     
  migrator:
    plugin: dump
    after: [evdev]
    source: .
    stage-packages:
      - zenity
    override-pull: |
      snapcraftctl pull
      chmod a+x migrate-config
    stage:
      - bin/migrate-config
      - usr/bin/zenity
      - usr/share/zenity
    organize:
      migrate-config: bin/migrate-config

  cleanup:
    after: [migrator]
    plugin: nil
    build-snaps: [core20, gtk-common-themes, gnome-3-38-2004]
    override-prime: |
      set -eux
      for snap in "core20" "gtk-common-themes" "gnome-3-38-2004"; do
          cd "/snap/$snap/current" && find . -type f,l -name *.so.* -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done   
